sudo: required
dist: trusty
group: edge

language: python  # workaround for not setting CC/CXX with default value

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - build-essential
      - cmake
      - gcc-5
      - g++-5
      - clang-format-3.9

before_install:
  - sudo add-apt-repository -y ppa:kojoley/boost
  - sudo apt-get -q update
  - sudo apt-get install -qq software-properties-common
  - sudo apt-get install -qq libgoogle-perftools-dev libzmq3-dev mercurial git
  - sudo apt-get -y install libboost-{chrono,program-options,date-time,thread,system,filesystem,regex,serialization}1.58{-dev,.0}

install:
  - mkdir tmp-zmq
  - cd tmp-zmq
  - git clone https://github.com/zeromq/cppzmq
  - cd cppzmq
  - git reset --hard 4648ebc9643119cff2a433dff4609f1a5cb640ec  # Since only libzmq3-dev can be installed. The new zmq.hpp requires version above 4.
  - sudo cp zmq.hpp /usr/local/include
  - cd ../..
  - rm -rf tmp-zmq

before_script:
  - export CLANG_FORMAT=clang-format-3.9
  - ./scripts/lint.py
  - ./scripts/clang-format.py -o check

matrix:
  include:
    - compiler: "gcc-5"
      env: CC=gcc-5 CXX=g++-5

script:
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_SHARED_LIBRARY=on ..
  - make -j4 HuskyUnitTest
  - ./HuskyUnitTest --gtest_shuffle  # To check if the order causes some time-out failures.
